### ISSUE TITLE
Module name problem on windows

### ISSUE THREAD

**Issue by asteria277** [craigburke/angular-template-asset-pipeline#14] opened 2015-01-29 10:30 UTC
Hi,

I'm currently using :
asset-pipeline 1.9.9
angular-template-asset-pipeline 1.3.0

And I'm trying to update to versions :
asset-pipeline:2.1.1
angular-template-asset-pipeline:2.0.3

Unfortunately, the module names generated by the plugin in the .js file are not valid anymore. For example :

/assets/my-app/app-section/templates/hello.js  Returns : 

```javascript
angular.module('myApp/appSection/templates/hello.tpl.htm').run(['$templateCache', function($templateCache) {
	$templateCache.put('hello.htm', '<h1>Hello World!</h1>');
}]);
```

With version 1.3.0, it got :

```javascript
angular.module('my-app/app-section').run(['$templateCache', function($templateCache) {
	$templateCache.put('hello.htm', '<h1>Hello World!</h1>');
}]);
```

Perhaps the problem is coming from the fact that you use File.separator to split the path. File.separator on windows is '\', but even on windows the path contains '/' ...

**Comment by craigburke** [comment] 2015-01-30 21:05
Yeah I'm betting that you're right. I'll take a look.

**Comment by craigburke** [comment] 2015-01-30 22:09
Give version 2.0.4 a try. It should fix your issue.

**Comment by asteria277** [comment] 2015-02-02 08:38
Thanks ... but I'm afraid I still have the same problem.

On Windows, both lines returns an array with only one item :
"myApp/appSection/templates/hello.tpl.htm".tokenize(Pattern.quote(File.separator))
"myApp/appSection/templates/hello.tpl.htm".tokenize("\")
===> [myApp/appSection/templates/hello.tpl.htm]

I think File.separator shouldn't be used, as the path contained in AssetFile is not a path that follows the current operating system conventions.

**Comment by craigburke** [comment] 2015-02-02 14:32
Well looks like I might have to fire up a Windows VM for this one. I'll give it anther try.

**Comment by asteria277** [comment] 2015-02-03 12:38
Thank you.
I will test the new version as soon as it is available.

**Comment by dmahapatro** [comment] 2015-02-08 03:48
@craigburke Looks like this [PR](https://github.com/craigburke/angular-template-asset-pipeline/pull/15) should solve this issue. 

I am also planning to upgrade Groovy version to 2.4.0 and asset pipeline to the latest version. That will be a separate PR and after some exploratory testing.

**Comment by craigburke** [comment] 2015-02-08 12:16
Thanks a lot @dmahapatro! I really appreciate that :smile: 

There's no harm in upgrading the version of the asset pipeline core, but I'd like to keep the Groovy version lower for folks using older versions of Grails. Thanks again for the PR!!

**Comment by dmahapatro** [comment] 2015-02-08 16:14
@craigburke You are most welcome. Any plans when to release v2.0.5 with this PR. I am planning to migrate a full fledged legacy angular based Grails app from resources to asset-pipeline ( I know it is high time that should have been done earlier, but you know corporate policies :) ). 

Now there is no excuse if we want to upgrade to Grails 3, I have to use asset-pipeline. :)

I wanted to ask a question related to this plugin. 
Why `*.tpl.html` instead of just `*.html` or `*.htm`? 

Is it because you did not want to put all the html files under `templates` in `$templateCache`.

**Comment by craigburke** [comment] 2015-02-08 18:37
@dmahapatro I'll probably cut 2.0.5 sometime Monday (I'll reply to this ticket when I do).

You'll never want to go back to Resources after that. Asset pipeline is awesome! :grinning: 

Your assumption about `tpl.html` vs `html` is correct. It's also just better to differentiate them as well since otherwise I'd be adding my processor to an already existing asset file type (HtmlAssetFile). This way there's just less chance for surprises.

**Comment by craigburke** [comment] 2015-02-09 18:33
Alright version 2.0.5 with @dmahapatro's PR is now live. @asteria277 does this resolve your issue?

**Comment by dmahapatro** [comment] 2015-02-09 18:42
Awesome. Thank you. 

Minor modification in README: 

From:
_In gradle these settings can be changed in your build.**config**_

To:
_In gradle these settings can be changed in your build.**gradle**_

**Comment by craigburke** [comment] 2015-02-09 18:43
@dmahapatro good catch! I changed it. 

I'll wait until I get confirmation from @asteria277 until I close this issue.

**Comment by asteria277** [comment] 2015-02-09 19:26
I will upgrade my app tomorrow morning at work, I will tell you the results asap.
Thanks already both of you !

**Comment by craigburke** [comment] 2015-02-09 20:59
@asteria277 when you do, use version 2.0.6 (not 2.0.5). I've confirmed that it works on Windows.

**Comment by asteria277** [comment] 2015-02-10 12:46
I've tested version 2.0.6 and I it is working for me ! Thanks again.

I just have another issue when building the war on hudson, but I will open another issue on the related git project.

**Comment by craigburke** [comment] 2015-02-10 12:53
@asteria277 awesome! :smile: 

@dmahapatro thanks again for helping to point me in the right direction on this. That's much appreciated.

**Closed by craigburke** 2015-02-10 12:53 UTC
